spring:
  jmx:
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
  jpa:
    # 配置方言com.zsoltfabok包中
    database-platform: org.hibernate.dialect.SQLiteDialect
    # 最好改成false，自己手动建表
    generate-ddl: false
    #jpa.hibernate.ddl-auto 仅支持create-drop和create

javafx:
  title: 工具集合
  stage:
    resizable: true
remine:
  login-url: http://10.1.121.122/redmine/login
  issues-new-url: http://10.1.121.122/redmine/projects/xjsocm/issues/new
gitlab:
  url: http://10.139.6.26:7077/


app:
  tool:
    dubbo:
      addrs: zookeeper://127.0.0.1:2181,zookeeper://10.139.8.160:2181


